server:
  port: 18881
  servlet:
    session:
      timeout: 30m  # Session timeout: 30 minutes
    context-path: /app-secret-path-a7b3c9d8

app:
  test-property: hello-world
  allowed-names:

# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://172.16.0.212:5432/dass2?currentSchema=other1&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: sde
    password: sde
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource # Specify Druid as the datasource type
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
  sql:
    init:
      mode: never
logging:
  level:
    com.example.geminispringboot.dao: debug
